("Indo-europees" A  ((((I n) 2) ((d o) 0)) (((2) 0) ((r o) 0) ((p e s) 1))))
("Indo-europees" N  ((((I n) 1) ((d o) 0)) (((2) 0) ((r o) 0) ((p e s) 2))))
("Indogermaans" A  ((((I n) 2) ((d o) 0)) (((G E r) 0) ((m a n s) 1))))
("Indogermaans" N  ((((I n) 1) ((d o) 0)) (((G E r) 0) ((m a n s) 2))))
("aangaande" A  ((((a N) 1)) (((G a n) 2) ((d @) 0))))
("aangaande" P  ((((a N) 0) ((G a n) 1) ((d @) 0))))
("achteruitgang" N ((((A x) 1) ((t @ r) 0)) (((Y+ t) 2) ((x A N) 0)))) 
("achteruitgang" N ((((A x) 2) ((t @ r) 0)) (((Y+ t) 1) ((x A N) 0)))) 
("adderen" N  ((((A) 1) ((d @) 0) ((r @ n) 0))))
("adderen" V  ((((A) 0) ((d e) 1) ((r @ n) 0))))
("ais" N  ((((A j s) 1))))
("ais" N  ((((a) 0) ((i s) 1))))
("appel" N ((((A) 1) ((p @ l) 0))))
("appel" N ((((A) 0) ((p E l) 1))))
("argwanend" A  ((((A r G) 1) ((w a) 0) ((n @ n t) 0))))
("argwanend" Adv  ((((A r G) 0) ((w a) 1) ((n @ n t) 0))))
("argwanende" A  ((((A r G) 1) ((w a) 0) ((n @ n) 0) ((d @) 0))))
("argwanende" N  ((((A r G) 0) ((w a) 1) ((n @ n) 0) ((d @) 0))))
("band" N ((((b A n t) 1))))
("band" N ((((b E n t) 1))))
("bar" N ((((b A r) 1))))
("bar" N ((((b a r) 1))))
("barrel" N ((((b A) 1) ((r @ l) 0))))
("barrel" N ((((b E) 1) ((r @ l) 0))))
("base" N ((((b e s) 1))))
("base" N ((((b a) 1) ((z @) 0))))
("bat" N  ((((b E t) 1))))
("bat" nil  ((((b A t) 1))))
("bedelen" V ((((b e) 1) ((d @) 0) ((l @ n) 0))))
("bedelen" V ((((b @) 0) ((d e) 1) ((l @ n) 0))))
("beken" N  ((((b e) 1) ((k @ n) 0))))
("beken" V  ((((b @) 0) ((k E n) 1))))
("bekeren" V ((((b e) 1) ((k @) 0) ((r @ n) 0))))
("bekeren" V ((((b @) 0) ((k e) 1) ((r @ n) 0))))
("beren" N  ((((b e) 1) ((r @ n) 0))))
("beren" V  ((((b @) 0) ((r E n) 1))))
("berend" A  ((((b e) 1) ((r @ n t) 0))))
("berend" V  ((((b @) 0) ((r E n t) 1))))
("berende" A  ((((b e) 1) ((r @ n) 0) ((d @) 0))))
("berende" V  ((((b @) 0) ((r E n) 1) ((d @) 0))))
("bete" nil  ((((b E:) 1) ((t @) 0))))
("bete" nil  ((((b e) 1) ((t @) 0))))
("beteren" V  ((((b @) 0) ((t e) 1) ((r @ n) 0))))
("beteren" V  ((((b e) 1) ((t @) 0) ((r @ n) 0))))
("betering" nil  ((((b e) 1) ((t @) 0) ((r I N) 0))))
("betering" nil  ((((b @) 0) ((t e) 1) ((r I N) 0))))
("beving" N  ((((b e) 1) ((v I N) 0))))
("beving" V  ((((b @) 0) ((v I N) 1))))
("bevingen" A  ((((b e) 1) ((v I) 0) ((N @ n) 0))))
("bevingen" V  ((((b @) 0) ((v I) 1) ((N @ n) 0))))
("bezie" V  ((((b @) 0) ((z i) 1))))
("bezie" nil ((((b e) 1) ((z i) 0))))
("blazer" N ((((b l e) 1) ((z @ r) 0))))
("blazer" N ((((b l a) 1) ((z @ r) 0))))
("boots" A  ((((b o t s) 1))))
("boots" N  ((((b u t s) 1))))
("béving" N ((((b e) 1) ((v I N) 0))))
("bête" nil ((((b E:) 1) ((t @) 0))))
("buitenmodel" N ((((b Y+) 1) ((t @) 0)) (((m o) 0) ((d E l) 2))))
("buitenmodel" N ((((b Y+) 2) ((t @) 0)) (((m o) 0) ((d E l) 1))))
("buitenspel" N ((((b Y+) 1) ((t @) 0)) (((s p E l) 2))))
("buitenspel" N ((((b Y+) 2) ((t @) 0)) (((s p E l) 1))))
("cederen" A  ((((s e) 1) ((d @) 0) ((r @ n) 0))))
("cederen" V  ((((s e) 0) ((d e) 1) ((r @ n) 0))))
("check" N  ((((S E k) 1))))
("check" V  ((((t S E k) 1))))
("conjunctief" A  ((((k O) 1) ((n j Y N k) 0) ((t i f) 0))))
("conjunctief" N  ((((k O) 0) ((n j Y N k) 0) ((t i f) 1))))
("chromaatgeel" N ((((x r o) 0) ((m a t) 1)) (((x e l) 2))))
("chromaatgeel" A ((((x r o) 0) ((m a t) 2)) (((x e l) 1))))
("chromaatgroen" A ((((x r o) 0) ((m a t) 1)) (((x r u n) 2))))
("chromaatgroen" A ((((x r o) 0) ((m a t) 2)) (((x r u n) 1))))
("chromaatrood" A ((((x r o) 0) ((m a t) 1)) (((r o t) 2))))
("chromaatrood" A ((((x r o) 0) ((m a t) 2)) (((r o t) 1))))
("colon" N ((((k o) 0) ((l O n) 1))))
("colon" N ((((k o) 1) ((l O n) 0))))
("comparatief" A ((((k O m) 0) ((p a) 0) ((r a) 0) ((t i f) 1))))
("comparatief" N ((((k O m) 1) ((p a) 0) ((r a) 0) ((t i f) 0))))
("credit" N ((((k r e) 1) ((d I t) 0))))
("credit" N ((((k r E) 1) ((d I t) 0))))
("curie" N  ((((k y) 0) ((r i) 1))))
("curie" N  ((((k y) 1) ((r i) 0))))
("datief" A ((((d a) 0) ((t i f) 1))))
("datief" N ((((d a) 1) ((t i f) 0))))
("deist" N  ((((d e) 0) ((j I s t) 1))))
("deist" V  ((((d E+ s t) 1))))
("dies" N  ((((d i) 0) ((j E s) 1))))
("dies" nil  ((((d i s) 1))))
("doodgoed" A ((((d o t) 2)) (((x u t) 1))))
("doodgoed" N ((((d o t) 1)) (((x u t) 2))))
("doodzonde" A ((((d o t) 2)) (((z O n) 1) ((d @) 0))))
("doodzonde" N ((((d o t) 1)) (((z O n) 2) ((d @) 0))))
("doorbladerde" A  ((((d o r) 2)) (((b l a) 1) ((d @ r) 0) ((d @) 0))))
("doorbladerde" V  ((((d o r) 1)) (((b l a) 2) ((d @ r) 0) ((d @) 0))))
("doorbloed" A  ((((d o r) 2)) (((b l u t) 1))))
("doorbloed" V  ((((d o r) 1)) (((b l u t) 2))))
("doorboorde" A  ((((d o r) 2)) (((b o r) 1) ((d @) 0))))
("doorboorde" V  ((((d o r) 1)) (((b o r) 2) ((d @) 0))))
("doorbreken" V ((((d o r) 1)) (((b r e) 2) ((k @ n) 0))))
("doorbreken" V ((((d o r) 2)) (((b r e) 1) ((k @ n) 0))))
("doordacht" A  ((((d o r) 2)) (((d A x t) 1))))
("doordacht" V  ((((d o r) 1)) (((d A x t) 2))))
("doordenken" V ((((d o r) 1)) (((d E N) 2) ((k @ n) 0))))
("doordenken" V ((((d o r) 2)) (((d E N) 1) ((k @ n) 0))))
("doordringen" V ((((d o r) 1)) (((d r I N) 2) ((k @ n) 0))))
("doordringen" V ((((d o r) 2)) (((d r I N) 1) ((k @ n) 0))))
("doorkliefde" A  ((((d o r) 2)) (((k l i v) 1) ((d @) 0))))
("doorkliefde" V  ((((d o r) 1)) (((k l i v) 2) ((d @) 0))))
("doorklinken" V ((((d o r) 1)) (((k l I N) 2) ((k @ n) 0))))
("doorklinken" V ((((d o r) 2)) (((k l I N) 1) ((k @ n) 0))))
("doorkruisen" V ((((d o r) 1)) (((k r Y+) 2) ((s @ n) 0))))
("doorkruisen" V ((((d o r) 2)) (((k r Y+) 1) ((s @ n) 0))))
("doorkruist" A  ((((d o r) 2)) (((k r Y+ s t) 1))))
("doorkruist" V  ((((d o r) 1)) (((k r Y+ s t) 2))))
("doorkruiste" A  ((((d o r) 2)) (((k r Y+ s) 1) ((t @) 0))))
("doorkruiste" V  ((((d o r) 1)) (((k r Y+ s) 2) ((t @) 0))))
("doorleven" V ((((d o r) 1)) (((l e) 2) ((v @ n) 0))))
("doorleven" V ((((d o r) 2)) (((l e) 1) ((v @ n) 0))))
("doorlopen" V ((((d o r) 1)) (((l o) 2) ((p @ n) 0))))
("doorlopen" V ((((d o r) 2)) (((l o) 1) ((p @ n) 0))))
("doorploegde" A  ((((d o r) 2)) (((p l u G) 1) ((d @) 0))))
("doorploegde" V  ((((d o r) 1)) (((p l u G) 2) ((d @) 0))))
("doorregen" A  ((((d o) 2)) (((r e) 1) ((G @ n) 0))))
("doorregen" V  ((((d o) 1)) (((r e) 2) ((G @ n) 0))))
("doorreisde" A  ((((d o) 2)) (((r E+ z) 1) ((d @) 0))))
("doorreisde" V  ((((d o) 1)) (((r E+ z) 2) ((d @) 0))))
("doorrookt" A  ((((d o) 0) ((r o k t) 1))))
("doorrookt" V  ((((d o) 1)) (((r o k t) 2))))
("doorrookte" A  ((((d o) 0)) (((r o k) 1) ((t @) 0))))
("doorrookte" A  ((((d o) 1)) (((r o k) 2) ((t @) 0))))
("doorscheurde" A  ((((d o r) 2)) (((s x 2 r) 1) ((d @) 0))))
("doorscheurde" V  ((((d o r) 1)) (((s x 2 r) 2) ((d @) 0))))
("doorsnuffelde" A  ((((d o r) 2)) (((s n Y) 1) ((f @ l) 0) ((d @) 0))))
("doorsnuffelde" V  ((((d o r) 1)) (((s n Y) 2) ((f @ l) 0) ((d @) 0))))
("doorspoelde" A  ((((d o r) 2)) (((s p u l) 1) ((d @) 0))))
("doorspoelde" V  ((((d o r) 1)) (((s p u l) 2) ((d @) 0))))
("doorstikt" A  ((((d o r) 2)) (((s t I k t) 1))))
("doorstikt" V  ((((d o r) 1)) (((s t I k t) 2))))
("doorstikte" A  ((((d o r) 2)) (((s t I k) 1) ((t @) 0))))
("doorstikte" V  ((((d o r) 1)) (((s t I k) 2) ((t @) 0))))
("doorstroomde" A  ((((d o r) 2)) (((s t r o m) 1) ((d @) 0))))
("doorstroomde" V  ((((d o r) 1)) (((s t r o m) 2) ((d @) 0))))
("doortast" A ((((d o r) 2)) (((t A s t) 1))))
("doortast" V  ((((d o r) 1)) (((t A s t) 2))))
("doortrapt" A  ((((d o r) 0) ((t r A p t) 1))))
("doortrapt" V  ((((d o r) 1)) (((t r A p t) 2))))
("doortrapte" A  ((((d o r) 0) ((t r A p) 1) ((t @) 0))))
("doortrapte" V  ((((d o r) 1)) (((t r A p) 2) ((t @) 0))))
("doorwaad" A  ((((d o r) 2)) (((w a t) 1))))
("doorwaad" V  ((((d o r) 1)) (((w a t) 2))))
("doorwandelde" A  ((((d o r) 2)) (((w A n) 1) ((d @ l) 0) ((d @) 0))))
("doorwandelde" V  ((((d o r) 1)) (((w A n) 2) ((d @ l) 0) ((d @) 0))))
("doorwarm" A  ((((d o r) 2)) (((w A r m) 1))))
("doorwarm" V  ((((d o r) 1)) (((w A r m) 2))))
("doorwerkt" A  ((((d o r) 2)) (((w E r k t) 1))))
("doorwerkt" V  ((((d o r) 1)) (((w E r k t) 2))))
("doorwerkte" A  ((((d o r) 2)) (((w E r k) 1) ((t @) 0))))
("doorwerkte" V  ((((d o r) 1)) (((w E r k) 2) ((t @) 0))))
("doorworstelde" A  ((((d o r) 2)) (((w O r) 1) ((s t @ l) 0) ((d @) 0))))
("doorworstelde" V  ((((d o r) 1)) (((w O r) 2) ((s t @ l) 0) ((d @) 0))))
("doorzocht" A  ((((d o r) 1)) (((z O x t) 2))))
("doorzocht" N  ((((d o r) 2)) (((z O x t) 1))))
("dubbelgebeide" nil  ((((d Y) 1) ((b @ l) 0)) (((G @) 0) ((b E+) 2) ((d @) 0))))
("dubbelgebeide" nil  ((((d Y) 2) ((b @ l) 0)) (((G @) 0) ((b E+) 1) ((d @) 0))))
("ecce-homo" nil ((((E k) 1) ((s @) 0)) (((h o) 2) ((m o) 0))))
("ecce-homo" nil ((((E t) 1) ((S @) 0)) (((h o) 2) ((m o) 0)))) 
("een" Art  ((((@ n) 0))))
("email" nil  ((((i) 1)) (((m e l) 2))))
("email" nil  ((((e) 0) ((m A j) 1))))
("evenaar" N  ((((e) 1) ((v @) 0) ((n a r) 0))))
("evenaar" V  ((((e) 0) ((v @) 0) ((n a r) 1))))
("file" N ((((f i) 1) ((l @) 0))))
("file" N ((((f a j l) 1))))
("frotte" N  ((((f r O) 0) ((t e) 1))))
("frotte" V  ((((f r O) 1) ((t @) 0))))
("gelijkgericht" nil  ((((x @) 0) ((l E+ k) 0) ((x @) 0) ((r I x t) 1))))
("gelijkgericht" nil  ((((x @) 0) ((l E+ k) 1)) (((x @) 0) ((r I x t) 2))))
("gelijkgerichte" nil  ((((x @) 0) ((l E+ k) 0) ((x @) 0) ((r I x) 1) ((t @) 0))))
("gelijkgerichte" nil  ((((x @) 0) ((l E+ k) 1)) (((x @) 0) ((r I x) 2) ((t @) 0))))
("gelijkgestemd" A  ((((x @) 0) ((l E+ k) 0) ((x @) 0) ((s t E m t) 1))))
("gelijkgestemd" V  ((((x @) 0) ((l E+ k) 1)) (((x @) 0) ((s t E m t) 2))))
("gelijkgestemde" N  ((((x @) 0) ((l E+ k) 0) ((x @) 0) ((s t E m) 1) ((d @) 0))))
("gelijkgestemde" V  ((((x @) 0) ((l E+ k) 1)) (((x @) 0) ((s t E m) 2) ((d @) 0))))
("gene" N  ((((Z E:) 1) ((n @) 0))))
("gene" nil  ((((x e) 1) ((n @) 0))))
("geren" N  ((((x @) 0) ((r E n) 1))))
("geren" V  ((((x e) 1) ((r @ n) 0))))
("gerend" V  ((((x @) 0) ((r E n t) 1))))
("gerend" nil  ((((x e) 1) ((r @ n t) 0))))
("gerende" V  ((((x @) 0) ((r E n) 1) ((d @) 0))))
("gerende" nil  ((((x e) 1) ((r @ n) 0) ((d @) 0))))
("gerén" V ((((G e) 0) ((r E n) 1))))
("goedkoop" N  ((((x u t) 1)) (((k o p) 2))))
("goedkoop" nil  ((((x u t) 2)) (((k o p) 1))))
("goedkóóp" nil ((((x u t) 0)) (((k o p) 1))))
("golf" N ((((G O l f) 1))))
("golf" N ((((g O l f) 1))))
("guts" N ((((G Y t s) 1))))
("guts" N ((((g Y t s) 1))))
("gêne" nil ((((Z e) 1) ((n @) 0))))
("halfvleugeligen" nil  ((((h A l) 0) ((f l 2) 1) ((G @) 0) ((l @) 0) ((G @ n) 0))))
("halfvleugeligen" nil  ((((h A l) 1)) (((f l 2) 2) ((G @) 0) ((l @) 0) ((G @ n) 0))))
("halfwassen" A  ((((h A l f) 2)) (((w A) 1) ((s @ n) 0))))
("halfwassen" N  ((((h A l f) 1)) (((w A) 2) ((s @ n) 0))))
("halfrond" N  ((((h A l f) 2)) (((r O n t) 1))))
("halfrond" N  ((((h A l f) 1)) (((r O n t) 2))))
("herbouw" N  ((((h E r) 1) ((b A+ w) 0))))
("herbouw" V  ((((h E r) 0) ((b A+ w) 1))))
("herdoop" N  ((((h E r) 1) ((d o p) 0))))
("herdoop" V  ((((h E r) 0) ((d o p) 1))))
("herdruk" N  ((((h E r) 1) ((d r Y k) 0))))
("herdruk" V  ((((h E r) 0) ((d r Y k) 1))))
("herdrukken" N  ((((h E r) 1) ((d r Y) 0) ((k @ n) 0))))
("herdrukken" V  ((((h E r) 0) ((d r Y) 1) ((k @ n) 0))))
("herijk" N  ((((h E r) 1) ((E+ k) 0))))
("herijk" V  ((((h E r) 0) ((E+ k) 1))))
("hertrouw" N  ((((h E r) 1) ((t r A+ w) 0))))
("hertrouw" V  ((((h E r) 0) ((t r A+ w) 1))))
("hm" nil ((((@ m) 1))))
("hm" nil ((((h E k) 1)((t o) 0)) (((m e) 2) ((t @ r) 0))))
("honderdjarige" A  ((((h O n) 1) ((d @ r d) 0)) (((j a) 2) ((r @) 0) ((G @) 0))))
("honderdjarige" N  ((((h O n) 2) ((d @ r d) 0)) (((j a) 1) ((r @) 0) ((G @) 0))))
("ijsvrij" A ((((E+ s) 1)) (((f r E+) 2))))
("ijsvrij" A ((((E+ s) 2)) (((f r E+) 1))))
("imperatief" A  ((((I m) 1) ((p @) 0) ((r a) 0) ((t i f) 0))))
("imperatief" N  ((((I m) 0) ((p @) 0) ((r a) 0) ((t i f) 1))))
("indicatief" A  ((((I n) 1) ((d i) 0) ((k a) 0) ((t i f) 0))))
("indicatief" N  ((((I n) 0) ((d i) 0) ((k a) 0) ((t i f) 1))))
("ingenue" nil  ((((E: n) 0) ((Z e) 0) ((n y) 1) ((w @) 0))))
("ingenue" nil  ((((E: n) 0) ((Z e) 0) ((n y) 1))))
("ingewikkeld" A  ((((I N) 0) ((G @) 0) ((w I) 1) ((k @ l t) 0))))
("ingewikkeld" V  ((((I N) 1)) (((G @) 0) ((w I) 2) ((k @ l t) 0))))
("ingewikkelde" nil  ((((I N) 0) ((G @) 0) ((w I) 1) ((k @ l) 0) ((d @) 0))))
("ingewikkelde" nil  ((((I N) 1)) (((G @) 0) ((w I) 2) ((k @ l) 0) ((d @) 0))))
("ingénue" nil ((((E: n) 0) ((Z e) 0) ((n y) 1) ((w @) 0))))
("interview" N  ((((I n) 1) ((t @ r) 0) ((v j u w) 0))))
("interview" V  ((((I n) 0) ((t @ r) 0) ((v j u w) 1))))
("inzittende" A  ((((I n) 1)) (((z I) 2) ((t @ n) 0) ((d @) 0))))
("inzittende" N  ((((I n) 2)) (((z I) 1) ((t @ n) 0) ((d @) 0))))
("item" N ((((i) 1) ((t E m) 0))))
("item" N ((((i) 1) ((t @ m) 0))))
("jaguar" N ((((d Z E) 1) ((g u) 0) ((w A r) 0))))
("jaguar" N ((((j a) 1) ((G y) 0) ((w A r) 0))))
("jam" N  ((((Z E m) 1))))
("jam" V  ((((d j E m) 1))))
("kalveren" N  ((((k A l) 1) ((v @) 0) ((r @ n) 0))))
("kalveren" V  ((((k A l) 1)) (((v e) 2) ((r @ n) 0))))
("kantelen" N  ((((k A n) 0) ((t e) 1) ((l @ n) 0))))
("kantelen" V  ((((k A n) 1) ((t @) 0) ((l @ n) 0))))
("kartel" N ((((k A r) 1) ((t @ l) 0))))
("kartel" N ((((k A r) 0) ((t E l) 1))))
("kartelvorming" N ((((k A r) 1) ((t E l) 0)) (((v o r) 2) ((m I N) 0))))
("kartelvorming" N ((((k A r) 0) ((t E l) 1)) (((v o r) 2) ((m I N) 0))))
("kenmerkend" A  ((((k E n) 0) ((m E r) 1) ((k @ n t) 0))))
("kenmerkend" V  ((((k E n) 1) ((m E r) 0) ((k @ n t) 0))))
("kenmerkende" A  ((((k E n) 0) ((m E r) 1) ((k @ n) 0) ((d @) 0))))
("kenmerkende" V  ((((k E n) 1)) (((m E r) 2) ((k @ n) 0) ((d @) 0))))
("kinderlijk" A ((((k I n) 1) ((d @ r) 0) ((l @ k) 0))))
("kinderlijk" N ((((k I n) 1) ((d @ r) 0)) (((l E+ k) 2))))
("kobaltblauw" A ((((k o) 0) ((b A l t) 1)) (((b l A+) 2))))
("kobaltblauw" A ((((k o) 0) ((b A l t) 2)) (((b l A+) 1))))
("komparatief" A  ((((k O m) 1) ((p a) 0) ((r a) 0) ((t i f) 0))))
("komparatief" N  ((((k O m) 0) ((p a) 0) ((r a) 0) ((t i f) 1))))
("konjunktief" A  ((((k O) 1) ((n j Y N k) 0) ((t i f) 0))))
("konjunktief" N  ((((k O) 0) ((n j Y N k) 0) ((t i f) 1))))
("koolzwart" A ((((k o l) 2)) (((z w A r t) 1))))
("koolzwart" N ((((k o l) 1)) (((z w A r t) 2))))
("kopergroen" N ((((k o) 1) ((p @ r) 0)) (((G r u n) 2))))
("kopergroen" A ((((k o) 2) ((p @ r) 0)) (((G r u n) 1))))
("koperrood" N ((((k o) 1) ((p @ r) 0)) (((r o t) 2))))
("koperrood" A ((((k o) 2) ((p @ r) 0)) (((r o t) 1))))
("lammeren" N  ((((l A) 1) ((m @) 0) ((r @ n) 0))))
("lammeren" V  ((((l A) 1)) (((m e) 2) ((r @ n) 0))))
("legende" A  ((((l e) 1) ((G @ n) 0) ((d @) 0))))
("legende" N  ((((l @) 0) ((G E n) 1) ((d @) 0))))
("legeren" V ((((l e) 1) ((G @) 0) ((r @ n) 0))))
("legeren" V ((((l @) 0) ((G e) 1) ((r @ n) 0))))
("legering" N ((((l e) 1) ((G @) 0) ((r I N) 0))))
("legering" N ((((l @) 0) ((G e) 1) ((r I N) 0))))
("levenslang" A  ((((l e) 1) ((v @ s) 0)) (((l A N) 2))))
("levenslang" N  ((((l e) 2) ((v @ s) 0)) (((l A N) 1))))
("lieren" N  ((((l i) 1) ((r @ n) 0))))
("lieren" V  ((((l i) 0) ((j e) 1) ((r @ n) 0))))
("liëren" nil ((((l i) 0) ((j e) 1) ((r @ n) 0))))
("lokatief" N ((((l o) 1) ((k a) 0) ((t i f) 0))))
("lokatief" A ((((l o) 0) ((k a) 0) ((t i f) 1))))
("look" N ((((l o k) 1))))
("look" N ((((l u k) 1))))
("loops" A  ((((l o p s) 1))))
("loops" N  ((((l u p s) 1))))
("maskeren" V ((((m A s) 1) ((k e) 0) ((r @ n) 0))))
("maskeren" V ((((m A s) 0) ((k e) 1) ((r @ n) 0))))
("medium" N ((((m e) 1) ((d i) 0) ((j @ m) 0))))
("medium" N ((((m i) 1) ((d i) 0) ((j @ m) 0))))
("Mercedes" N ((((m @ r) 0) ((s e) 1) ((d @ s) 0))))
("Mercedes" N ((((m E r) 0) ((s e) 1) ((d E s) 0))))
("misbaar" A ((((m I s) 1) ((b a r) 0))))
("misbaar" N ((((m I s) 0) ((b a r) 1))))
("misbakken" A  ((((m I z) 2)) (((b A) 1) ((k @ n) 0))))
("misbakken" V  ((((m I z) 1)) (((b A) 2) ((k @ n) 0))))
("misbruik" N  ((((m I z) 1) ((b r Y+ k) 0))))
("misbruik" V  ((((m I z) 0) ((b r Y+ k) 1))))
("misbruiken" N  ((((m I z) 1)) (((b r Y+) 2) ((k @ n) 0))))
("misbruiken" V  ((((m I z) 2)) (((b r Y+) 1) ((k @ n) 0))))
("misdadiger" A  ((((m I z) 2)) (((d a) 1) ((d @) 0) ((G @ r) 0))))
("misdadiger" N  ((((m I z) 1)) (((d a) 2) ((d @) 0) ((G @ r) 0))))
("misdrijf" N  ((((m I z) 1)) (((d r E+ f) 2))))
("misdrijf" V  ((((m I z) 2)) (((d r E+ f) 1))))
("misdrijven" N  ((((m I z) 1)) (((d r E+) 2) ((v @ n) 0))))
("misdrijven" V  ((((m I z) 2)) (((d r E+) 1) ((v @ n) 0))))
("miskoop" N  ((((m I s) 1)) (((k o p) 2))))
("miskoop" V  ((((m I s) 2)) (((k o p) 1))))
("miskopen" N  ((((m I s) 1)) (((k o) 2) ((p @ n) 0))))
("miskopen" V  ((((m I s) 2)) (((k o) 1) ((p @ n) 0))))
("mislezen" A  ((((m I s) 1)) (((l e) 2) ((z @ n) 0))))
("mislezen" V  ((((m I s) 2)) (((l e) 1) ((z @ n) 0))))
("mispakt" A  ((((m I s) 2)) (((p A k t) 1))))
("mispakt" V  ((((m I s) 1)) (((p A k t) 2))))
("mispakte" A  ((((m I s) 2)) (((p A k) 1) ((t @) 0))))
("mispakte" V  ((((m I s) 1)) (((p A k) 2) ((t @) 0))))
("misprijzen" N  ((((m I s) 2)) (((p r E+) 1) ((z @ n) 0))))
("misprijzen" V  ((((m I s) 1)) (((p r E+) 2) ((z @ n) 0))))
("misraden" V  ((((m I s) 2)) (((r a) 1) ((d @ n) 0))))
("misraden" V  ((((m I s) 1)) (((r a) 2) ((d @ n) 0))))
("misvallen" V  ((((m I s) 2)) (((v A) 1) ((l @ n) 0))))
("misvallen" V  ((((m I s) 1)) (((v A) 2) ((l @ n) 0))))
("misrekende" A  ((((m I s) 2)) (((r e) 1) ((k @ n) 0) ((d @) 0))))
("misrekende" V  ((((m I s) 1)) (((r e) 2) ((k @ n) 0) ((d @) 0))))
("mistelde" V  ((((m I s) 1)) (((t E l) 2) ((d @) 0))))
("mistelde" nil  ((((m I s) 2)) (((t E l) 1) ((d @) 0))))
("mistrouwen" nil  ((((m I s) 1)) (((t r A+) 2) ((w @ n) 0))))
("mistrouwen" nil  ((((m I s) 2)) (((t r A+) 1) ((w @ n) 0))))
("misval" nil  ((((m I s) 1)) (((f A l) 2))))
("misval" nil  ((((m I s) 2)) (((f A l) 1))))
("mobile" A  ((((m o) 0) ((b i) 1) ((l @) 0))))
("mobile" N  ((((m o) 1) ((b i) 0) ((l @) 0))))
("mores" N ((((m o) 1) ((r @ s) 0))))
("mores" N ((((m o) 1) ((r E s) 0))))
("multipel" nil  ((((m Y l) 0) ((t i) 1) ((p @ l) 0))))
("multipel" nil  ((((m Y l) 1) ((t i) 0) ((p @ l) 0))))
("naturen" N  ((((n a) 0) ((t y) 1) ((r @ n) 0))))
("naturen" V  ((((n a) 1)) (((t y) 2) ((r @ n) 0))))
("negeren" V ((((n @) 0) ((G e) 1) ((r @ n) 0))))
("negeren" V ((((n e) 1) ((G @) 0) ((r @ n) 0))))
("neuriet" N  ((((n 2) 0) ((r i t) 1))))
("neuriet" V  ((((n 2) 1) ((r i t) 0))))
("nominatief" A  ((((n o) 1) ((m i) 0) ((n a) 0) ((t i f) 0))))
("nominatief" N  ((((n o) 0) ((m i) 0) ((n a) 0) ((t i f) 1))))
("olijfgroen" N ((((o) 0) ((l E+ f) 1)) (((x r u n) 2))))
("olijfgroen" A ((((o) 0) ((l E+ f) 2)) (((x r u n) 1))))
("ombinden" V ((((O m) 1) ((b I n) 0) ((d @ n) 0))))
("ombinden" V ((((O m) 0) ((b I n) 1) ((d @ n) 0))))
("omboord" A  ((((O m) 2)) (((b o r t) 1))))
("omboord" V  ((((O m) 1)) (((b o r t) 2))))
("omgeven" V ((((O m) 1) ((G e) 0) ((v @ n) 0))))
("omgeven" V ((((O m) 0) ((G e) 1) ((v @ n) 0))))
("omgord" A  ((((O m) 2)) (((G O r t) 1))))
("omgord" V  ((((O m) 1)) (((G O r t) 2))))
("omhangen" V ((((O m) 1) ((h A) 0) ((N @ n) 0))))
("omhangen" V ((((O m) 0) ((h A) 1) ((N @ n) 0))))
("omkleden" V ((((O m) 1) ((k l e) 0) ((d @ n) 0))))
("omkleden" V ((((O m) 0) ((k l e) 1) ((d @ n) 0))))
("omkleed" A  ((((O m) 2)) (((k l e t) 1))))
("omkleed" V  ((((O m) 1)) (((k l e t) 2))))
("omlegde" A  ((((O m) 2)) (((l E G) 1) ((d @) 0))))
("omlegde" V  ((((O m) 1)) (((l E G) 2) ((d @) 0))))
("omplant" A  ((((O m) 2)) (((p l A n t) 1))))
("omplant" V  ((((O m) 1)) (((p l A n t) 2))))
("omslingerde" A  ((((O m) 2)) (((s l I) 1) ((N @ r) 0) ((d @) 0))))
("omslingerde" V  ((((O m) 1)) (((s l I) 2) ((N @ r) 0) ((d @) 0))))
("omsnoerde" A  ((((O m) 2)) (((s n u r) 1) ((d @) 0))))
("omsnoerde" V  ((((O m) 1)) (((s n u r) 2) ((d @) 0))))
("omspeelde" A  ((((O m) 2)) (((s p e l) 1) ((d @) 0))))
("omspeelde" V  ((((O m) 1)) (((s p e l) 2) ((d @) 0))))
("omspoelde" A  ((((O m) 2)) (((s p u l) 1) ((d @) 0))))
("omspoelde" V  ((((O m) 1)) (((s p u l) 2) ((d @) 0))))
("omstikt" A  ((((O m) 2)) (((s t I k t) 1))))
("omstikt" V  ((((O m) 1)) (((s t I k t) 2))))
("omstikte" A  ((((O m) 2)) (((s t I k) 1) ((t @) 0))))
("omstikte" V  ((((O m) 1)) (((s t I k) 2) ((t @) 0))))
("omstuwde" A  ((((O m) 2)) (((s t y w) 1) ((d @) 0))))
("omstuwde" V  ((((O m) 1)) (((s t y w) 2) ((d @) 0))))
("omwaaide" A  ((((O m) 2)) (((w a j) 1) ((d @) 0))))
("omwaaide" V  ((((O m) 1)) (((w a j) 2) ((d @) 0))))
("omwikkelde" A  ((((O m) 1)) (((w I) 2) ((k @ l) 0) ((d @) 0))))
("omwikkelde" V  ((((O m) 2)) (((w I) 1) ((k @ l) 0) ((d @) 0))))
("omwoelde" A  ((((O m) 2)) (((w u l) 1) ((d @) 0))))
("omwoelde" V  ((((O m) 1)) (((w u l) 2) ((d @) 0))))
("omzeilde" A  ((((O m) 2)) (((z E+ l) 1) ((d @) 0))))
("omzeilde" V  ((((O m) 1)) (((z E+ l) 2) ((d @) 0))))
("omzet" V  ((((O m) 0) ((z E t) 1))))
("omzet" nil  ((((O m) 1) ((z E t) 0))))
("omzette" nil  ((((O m) 0) ((z E) 1) ((t @) 0))))
("omzette" nil  ((((O m) 1)) (((z E) 2) ((t @) 0))))
("omzetten" nil  ((((O m) 0) ((z E) 1) ((t @ n) 0))))
("omzetten" nil  ((((O m) 1) ((z E) 0) ((t @ n) 0))))
("omzoomde" A  ((((O m) 2)) (((z o m) 1) ((d @) 0))))
("omzoomde" V  ((((O m) 1)) (((z o m) 2) ((d @) 0))))
("omzweefde" A  ((((O m) 2)) (((z w e v) 1) ((d @) 0))))
("omzweefde" V  ((((O m) 1)) (((z w e v) 2) ((d @) 0))))
("omzwermde" A  ((((O m) 1)) (((z w E r m) 2) ((d @) 0))))
("omzwermde" V  ((((O m) 2)) (((z w E r m) 1) ((d @) 0))))
("onderbouw" N  ((((O n) 1) ((d @ r) 0)) (((b A+ w) 2))))
("onderbouw" V  ((((O n) 2) ((d @ r) 0)) (((b A+ w) 1))))
("onderdrukt" nil  ((((O n) 0) ((d @ r) 0) ((d r Y k t) 1))))
("onderdrukt" nil  ((((O n) 1) ((d @ r) 0)) (((d r Y k t) 2))))
("onderdrukte" nil  ((((O n) 0) ((d @ r) 0) ((d r Y k) 1) ((t @) 0))))
("onderdrukte" nil  ((((O n) 1) ((d @ r) 0) ((d r Y k) 0) ((t @) 0))))
("onderdrukken" V  ((((O n) 0) ((d @ r) 0) ((d r Y) 1) ((k @ n) 0))))
("onderdrukken" V  ((((O n) 1) ((d @ r) 0) ((d r Y) 0) ((k @ n) 0))))
("ondergaan" V  ((((O n) 0) ((d @ r) 0) ((G a n) 1))))
("ondergaan" V  ((((O n) 1) ((d @ r) 0) ((G a n) 0))))
("ondergraven" V  ((((O n) 0) ((d @ r) 0) ((G r a) 1) ((v @ n) 0))))
("ondergraven" V  ((((O n) 1) ((d @ r) 0) ((G r a) 0) ((v @ n) 0))))
("onderhand" nil  ((((O n) 1) ((d @ r) 0)) (((h A n t) 2))))
("onderhand" nil  ((((O n) 2) ((d @ r) 0)) (((h A n t) 1))))
("onderhouden" V  ((((O n) 0) ((d @ r) 0) ((h A+) 1) ((d @ n) 0))))
("onderhouden" V  ((((O n) 1) ((d @ r) 0) ((h A+) 0) ((d @ n) 0))))
("onderkomen" A  ((((O n) 0) ((d @ r) 0) ((k o) 1) ((m @ n) 0))))
("onderkomen" N  ((((O n) 1) ((d @ r) 0) ((k o) 0) ((m @ n) 0))))
("onderlegde" nil  ((((O n) 0) ((d @ r) 0) ((l E G) 1) ((d @) 0))))
("onderlegde" nil  ((((O n) 1) ((d @ r) 0)) (((l E G) 2) ((d @) 0))))
("onderlijn" N  ((((O n) 1) ((d @ r) 0)) (((l E+ n) 2))))
("onderlijn" V  ((((O n) 2) ((d @ r) 0)) (((l E+ n) 1))))
("onderlijnen" N  ((((O n) 1) ((d @ r) 0)) (((l E+) 2) ((n @ n) 0))))
("onderlijnen" V  ((((O n) 2) ((d @ r) 0)) (((l E+) 1) ((n @ n) 0))))
("onderricht" N  ((((O n) 1) ((d @) 0) ((r I x t) 0))))
("onderricht" V  ((((O n) 0) ((d @) 0) ((r I x t) 1))))
("onderscheid" N  ((((O n) 1) ((d @ r) 0) ((s x E+ t) 0))))
("onderscheid" V  ((((O n) 2) ((d @ r) 0)) (((s x E+ t) 1))))
("onderspoelen" nil  ((((O n) 0) ((d @ r) 0) ((s p u) 1) ((l @ n) 0))))
("onderspoelen" nil  ((((O n) 1) ((d @ r) 0) ((s p u) 0) ((l @ n) 0))))
("onderstel" N  ((((O n) 1) ((d @ r) 0)) (((s t E l) 2))))
("onderstel" V  ((((O n) 2) ((d @ r) 0)) (((s t E l) 1))))
("onderstoppen" nil  ((((O n) 0) ((d @ r) 0) ((s t O) 1) ((p @ n) 0))))
("onderstoppen" nil  ((((O n) 1) ((d @ r) 0) ((s t O) 0) ((p @ n) 0))))
("onderstellen" N  ((((O n) 1) ((d @ r) 0)) (((s t E) 2) ((l @ n) 0))))
("onderstellen" V  ((((O n) 2) ((d @ r) 0)) (((s t E) 1) ((l @ n) 0))))
("onderstuurd" nil  ((((O n) 0) ((d @ r) 0) ((s t y r t) 1))))
("onderstuurd" nil  ((((O n) 1) ((d @ r) 0) ((s t y r t) 0))))
("ondertrouw" N  ((((O n) 1) ((d @ r) 0)) (((t r A+ w) 2))))
("ondertrouw" V  ((((O n) 2) ((d @ r) 0)) (((t r A+ w) 1))))
("onderwijs" N  ((((O n) 1) ((d @ r) 0)) (((w E+ s) 2))))
("onderwijs" V  ((((O n) 2) ((d @ r) 0)) (((w E+ s) 1))))
("onderwind" nil  ((((O n) 1) ((d @ r) 0)) (((w I n t) 2))))
("onderwind" nil  ((((O n) 2) ((d @ r) 0)) (((w I n t) 1))))
("onderwinden" nil  ((((O n) 1) ((d @ r) 0)) (((w I n) 2) ((d @ n) 0))))
("onderwinden" nil  ((((O n) 2) ((d @ r) 0)) (((w I n) 1) ((d @ n) 0))))
("onderzet" nil  ((((O n) 1) ((d @ r) 0)) (((z E t) 2))))
("onderzet" nil  ((((O n) 2) ((d @ r) 0)) (((z E t) 1))))
("onderzette" nil  ((((O n) 1) ((d @ r) 0)) (((z E) 2) ((t @) 0))))
("onderzette" nil  ((((O n) 2) ((d @ r) 0)) (((z E) 1) ((t @) 0))))
("onderzetten" nil  ((((O n) 1) ((d @ r) 0) ((z E) 0) ((t @ n) 0))))
("onderzetten" nil  ((((O n) 0) ((d @ r) 0) ((z E) 1) ((t @ n) 0))))
("onderzoek" N  ((((O n) 1) ((d @ r) 0)) (((z u k) 2))))
("onderzoek" V  ((((O n) 2) ((d @ r) 0)) (((z u k) 1))))
("ongans" A ((((O n) 0) ((G A n s) 1))))
("ongans" N ((((O n) 1) ((G A n s) 0))))
("ongelijk" A  ((((O N) 0) ((G @) 0) ((l E+ k) 1))))
("ongelijk" N  ((((O N) 1)) (((G @) 0) ((l E+ k) 2))))
("ongemotiveerd" nil  ((((O N) 0) ((G @) 0) ((m o) 0) ((t i) 0) ((v e r t) 1))))
("ongemotiveerd" nil  ((((O N) 1) ((G @) 0) ((m o) 0) ((t i) 0) ((v e r t) 0))))
("ongemotiveerde" nil  ((((O N) 1)) (((G @) 0) ((m o) 0) ((t i) 0) ((v e r) 2) ((d @) 0))))
("ongemotiveerde" nil  ((((O N) 2)) (((G @) 0) ((m o) 0) ((t i) 0) ((v e r) 1) ((d @) 0))))
("ongemotiveerder" nil  ((((O N) 1)) (((G @) 0) ((m o) 0) ((t i) 0) ((v e r) 2) ((d @ r) 0))))
("ongemotiveerder" nil  ((((O N) 2)) (((G @) 0) ((m o) 0) ((t i) 0) ((v e r) 1) ((d @ r) 0))))
("ongemotiveerdere" nil  ((((O N) 0) ((G @) 0) ((m o) 0) ((t i) 0) ((v e r) 1) ((d @) 0) ((r @) 0))))
("ongemotiveerdere" nil  ((((O N) 1)) (((G @) 0) ((m o) 0) ((t i) 0) ((v e r) 2) ((d @) 0) ((r @) 0))))
("ongemotiveerdst" nil  ((((O N) 0) ((G @) 0) ((m o) 0) ((t i) 0) ((v e r t s t) 1))))
("ongemotiveerdst" nil  ((((O N) 1)) (((G @) 0) ((m o) 0) ((t i) 0) ((v e r t s t) 2))))
("ongemotiveerdste" nil  ((((O N) 0) ((G @) 0) ((m o) 0) ((t i) 0) ((v e r t) 1) ((s t @) 0))))
("ongemotiveerdste" nil  ((((O N) 1)) (((G @) 0) ((m o) 0) ((t i) 0) ((v e r t) 2) ((s t @) 0))))
("onnut" A  ((((O) 0) ((n Y t) 1))))
("onnut" N  ((((O) 1) ((n Y t) 0))))
("ontrouw" A  ((((O n) 2)) (((t r A+ w) 1))))
("ontrouw" N  ((((O n) 1)) (((t r A+ w) 2))))
("onwaarde" A  ((((O n) 2)) (((w a r) 1) ((d @) 0))))
("onwaarde" N  ((((O n) 1)) (((w a r) 2) ((d @) 0))))
("operator" N ((((o) 0) ((p e) 0) ((r a) 1) ((t O r) 0))))
("operator" N ((((O) 0) ((p @) 0) ((r e) 1) ((t @ r) 0))))
("oppers" nil  ((((O) 1) ((p @ r s) 0))))
("oppers" nil  ((((O) 1)) (((p E r s) 2))))
("opperst" nil  ((((O) 1) ((p @ r s t) 0))))
("opperst" nil  ((((O) 1)) (((p E r s t) 2))))
("opperste" A  ((((O) 1) ((p @ r s) 0) ((t @) 0))))
("opperste" V  ((((O) 1)) (((p E r s) 2) ((t @) 0))))
("optatief" nil  ((((O p) 0) ((t a) 0) ((t i f) 1))))
("optatief" nil  ((((O p) 1) ((t a) 0) ((t i f) 0))))
("optativus" nil  ((((O p) 0) ((t a) 0) ((t i) 1) ((v Y s) 0))))
("optativus" nil  ((((O p) 1) ((t a) 0) ((t i) 0) ((v Y s) 0))))
("opteren" nil  ((((O p) 0) ((t e) 1) ((r @ n) 0))))
("opteren" nil  ((((O p) 1) ((t e) 0) ((r @ n) 0))))
("overbelast" A  ((((o) 1) ((v @ r) 0)) (((b @) 0) ((l A s t) 2))))
("overbelast" V  ((((o) 2) ((v @ r) 0)) (((b @) 0) ((l A s t) 1))))
("overbieden" V ((((o) 2) ((v @ r) 0)) (((b i) 1) ((d @ n) 0))))
("overbieden" V ((((o) 1) ((v @ r) 0)) (((b i) 2) ((d @ n) 0))))
("overboeken" V ((((o) 2) ((v @ r) 0)) (((b u) 1) ((k @ n) 0))))
("overboeken" V ((((o) 1) ((v @ r) 0)) (((b u) 2) ((k @ n) 0))))
("overbracht" nil  ((((o) 1) ((v @ r) 0)) (((b r A x t) 2))))
("overbracht" nil  ((((o) 2) ((v @ r) 0)) (((b r A x t) 1))))
("overdek" N  ((((o) 1) ((v @ r) 0)) (((d E k) 2))))
("overdek" V  ((((o) 2) ((v @ r) 0)) (((d E k) 1))))
("overdekken" N  ((((o) 1) ((v @ r) 0)) (((d E) 2) ((k @ n) 0))))
("overdekken" V  ((((o) 2) ((v @ r) 0)) (((d E) 1) ((k @ n) 0))))
("overdrijven" N  ((((o) 1) ((v @ r) 0) ((d r E+) 0) ((v @ n) 0))))
("overdrijven" V  ((((o) 0) ((v @ r) 0) ((d r E+) 1) ((v @ n) 0))))
("overgieten" N  ((((o) 1) ((v @ r) 0) ((G i) 0) ((t @ n) 0))))
("overgieten" V  ((((o) 0) ((v @ r) 0) ((G i) 1) ((t @ n) 0))))
("overhand" N  ((((o) 1) ((v @ r) 0)) (((h A n t) 2))))
("overhand" nil  ((((o) 2) ((v @ r) 0)) (((h A n t) 1))))
("overjaagde" nil  ((((o) 2) ((v @ r) 0)) (((j a G) 1) ((d @) 0))))
("overjaagde" nil  ((((o) 1) ((v @ r) 0)) (((j a G) 2) ((d @) 0))))
("overkomen" V ((((o) 2) ((v @ r) 0)) (((k o) 1) ((m @ n) 0))))
("overkomen" V ((((o) 1) ((v @ r) 0)) (((k o) 0) ((m @ n) 0))))
("overladen" V ((((o) 2) ((v @ r) 0)) (((l a) 1) ((d @ n) 0))))
("overladen" V ((((o) 1) ((v @ r) 0)) (((l a) 0) ((d @ n) 0))))
("overlap" N  ((((o) 1) ((v @ r) 0)) (((l A p) 2))))
("overlap" V  ((((o) 2) ((v @ r) 0)) (((l A p) 1))))
("overlappen" N  ((((o) 1) ((v @ r) 0)) (((l A) 2) ((p @ n) 0))))
("overlappen" V  ((((o) 2) ((v @ r) 0)) (((l A) 1) ((p @ n) 0))))
("overlast" N  ((((o) 1) ((v @ r) 0) ((l A s t) 0))))
("overlast" nil  ((((o) 2) ((v @ r) 0)) (((l A s t) 1))))
("overleg" nil  ((((o) 1) ((v @ r) 0)) (((l E x) 2))))
("overleg" nil  ((((o) 2) ((v @ r) 0)) (((l E x) 1))))
("overlegde" nil  ((((o) 1) ((v @ r) 0)) (((l E G) 2) ((d @) 0))))
("overlegde" nil  ((((o) 2) ((v @ r) 0)) (((l E G) 1) ((d @) 0))))
("overleggen" nil  ((((o) 1) ((v @ r) 0) ((l E) 0) ((G @ n) 0))))
("overleggen" nil  ((((o) 0) ((v @ r) 0) ((l E) 1) ((G @ n) 0))))
("overlopen" nil  ((((o) 1) ((v @ r) 0) ((l o) 0) ((p @ n) 0))))
("overlopen" nil  ((((o) 0) ((v @ r) 0) ((l o) 1) ((p @ n) 0))))
("overman" nil  ((((o) 1) ((v @ r) 0)) (((m A n) 2))))
("overman" nil  ((((o) 2) ((v @ r) 0)) (((m A n) 1))))
("overmatig" nil  ((((o) 0) ((v @ r) 0) ((m a) 1) ((t @ x) 0))))
("overmatig" nil  ((((o) 1) ((v @ r) 0)) (((m a) 2) ((t @ x) 0))))
("overmatige" nil  ((((o) 0) ((v @ r) 0) ((m a) 1) ((t @) 0) ((G @) 0))))
("overmatige" nil  ((((o) 1) ((v @ r) 0)) (((m a) 2) ((t @) 0) ((G @) 0))))
("overpraat" nil  ((((o) 1) ((v @ r) 0)) (((p r a t) 2))))
("overpraat" nil  ((((o) 2) ((v @ r) 0)) (((p r a t) 1))))
("overreed" nil  ((((o) 1) ((v @) 0)) (((r e t) 2))))
("overreed" nil  ((((o) 2) ((v @) 0)) (((r e t) 1))))
("overrijden" nil  ((((o) 1) ((v @ r) 0) ((r E+) 0) ((d @ n) 0))))
("overrijden" nil  ((((o) 0) ((v @ r) 0) ((r E+) 1) ((d @ n) 0))))
("overschatte" nil  ((((o) 0) ((v @ r) 0) ((s x A) 1) ((t @) 0))))
("overschatte" nil  ((((o) 1) ((v @ r) 0)) (((s x A) 2) ((t @) 0))))
("overschilderde" A  ((((o) 2) ((v @ r) 0)) (((s x I l) 1) ((d @ r) 0) ((d @) 0))))
("overschilderde" V  ((((o) 1) ((v @ r) 0)) (((s x I l) 2) ((d @ r) 0) ((d @) 0))))
("overspeelde" nil  ((((o) 1) ((v @ r) 0)) (((s p e l) 2) ((d @) 0))))
("overspeelde" nil  ((((o) 2) ((v @ r) 0)) (((s p e l) 1) ((d @) 0))))
("overstemde" nil  ((((o) 1) ((v @ r) 0)) (((s t E m) 2) ((d @) 0))))
("overstemde" nil  ((((o) 2) ((v @ r) 0)) (((s t E m) 1) ((d @) 0))))
("overstroomde" nil  ((((o) 1) ((v @ r) 0)) (((s t r o m) 2) ((d @) 0))))
("overstroomde" nil  ((((o) 2) ((v @ r) 0)) (((s t r o m) 1) ((d @) 0))))
("overstuur" A  ((((o) 0) ((v @ r) 0) ((s t y r) 1))))
("overstuur" V  ((((o) 1) ((v @ r) 0)) (((s t y r) 2))))
("overstuurde" A  ((((o) 0) ((v @ r) 0) ((s t y r) 1) ((d @) 0))))
("overstuurde" nil  ((((o) 1) ((v @ r) 0)) (((s t y r) 2) ((d @) 0))))
("overtekende" nil  ((((o) 1) ((v @ r) 0)) (((t e) 2) ((k @ n) 0) ((d @) 0))))
("overtekende" nil  ((((o) 2) ((v @ r) 0)) (((t e) 1) ((k @ n) 0) ((d @) 0))))
("overtroefde" nil  ((((o) 1) ((v @ r) 0)) (((t r u v) 2) ((d @) 0))))
("overtroefde" nil  ((((o) 2) ((v @ r) 0)) (((t r u v) 1) ((d @) 0))))
("overvoerde" nil  ((((o) 1) ((v @ r) 0)) (((v u r) 2) ((d @) 0))))
("overvoerde" nil  ((((o) 2) ((v @ r) 0)) (((v u r) 1) ((d @) 0))))
("overvraagde" nil  ((((o) 1) ((v @ r) 0)) (((v r a G) 2) ((d @) 0))))
("overvraagde" nil  ((((o) 2) ((v @ r) 0)) (((v r a G) 1) ((d @) 0))))
("overweg" ADV  ((((o) 2) ((v @ r) 0)) (((w E x) 1))))
("overweg" N  ((((o) 1) ((v @ r) 0)) (((w E x) 2))))
("overwonnen" A  ((((o) 1) ((v @ r) 0)) (((w O) 2) ((n @ n) 0))))
("overwonnen" V  ((((o) 0) ((v @ r) 0) ((w O) 1) ((n @ n) 0))))
("overzeilde" A  ((((o) 1) ((v @ r) 0)) (((z E+ l) 2) ((d @) 0))))
("overzeilde" A  ((((o) 2) ((v @ r) 0)) (((z E+ l) 1) ((d @) 0))))
("overzij" N  ((((o) 1) ((v @ r) 0)) (((z E+) 2))))
("overzij" V  ((((o) 2) ((v @ r) 0)) (((z E+) 1))))
("passief" N ((((p A) 2)) (((s i f) 1))))
("passief" nil  ((((p A) 0) ((s i f) 1))))
("pinas" N ((((p I n) 1)) (((A s) 2))))
("pinas" N ((((p i) 0) ((n A s) 1))))
("piste" N  ((((p i s) 1) ((t @) 0))))
("piste" V  ((((p I s) 1) ((t @) 0))))
("pisten" N  ((((p i s) 1) ((t @ n) 0))))
("pisten" V  ((((p I s) 1) ((t @ n) 0))))
("pool" N ((((p o l) 1))))
("pool" N ((((p u l) 1))))
("poster" N ((((p o s) 1) ((t @ r) 0))))
("poster" N ((((p O s) 1) ((t @ r) 0))))
("punteren" V ((((p Y n) 1) ((t @) 0) ((r @ n) 0))))
("punteren" V ((((p Y n) 0) ((t e) 1) ((r @ n) 0))))
("quote" N ((((k w o t) 1))))
("quote" N ((((k w o) 1) ((t @) 0))))
("raderen" V ((((r a) 1) ((d @) 0) ((r @ n) 0))))
("raderen" V ((((r a) 0) ((d e) 1) ((r @ n) 0))))
("rap" N ((((r A p) 1))))
("rap" N ((((r E p) 1))))
("rappen" V ((((r A p) 1) ((p @ n) 0))))
("rappen" V ((((r E p) 1) ((p @ n) 0))))
("rapport" N ((((r A p) 0) ((p O r) 1))))
("rapport" N ((((r A p) 0) ((p O r t) 1))))
("rataplan" N  ((((r A) 1) ((t a) 0) ((p l A n) 0))))
("rataplan" nil  ((((r A) 0) ((t a) 0) ((p l A n) 1))))
("regent" N  ((((r @) 0) ((G E n t) 1))))
("regent" V  ((((r e) 1) ((G @ n t) 0))))
("rollende" A  ((((r O) 1) ((l @ n) 0) ((d @) 0))))
("rollende" N  ((((r O) 2)) (((l E n) 1) ((d @) 0))))
("sapgroen" N ((((s A p) 1)) (((G r u n) 2))))
("sapgroen" A ((((s A p) 2)) (((G r u n) 1))))
("savojekool" N ((((s A) 0) ((v o) 1) ((j @) 0)) (((k o l) 2))))
("savojekool" N ((((s A) 0) ((v o) 2) ((j @) 0)) (((k o l) 1))))
("scharlakenrood" N ((((s x A r) 0) ((l a) 1) ((k @ n) 0)) (((r o t) 2))))
("scharlakenrood" A ((((s x A r) 0) ((l a) 2) ((k @ n) 0)) (((r o t) 1))))
("slabak" A  ((((s l a) 2)) (((b A k) 1))))
("slabak" N  ((((s l a) 1)) (((b A k) 2))))
("slabakken"  A ((((s l a) 2)) (((b A) 1) ((k @ n) 0))))
("slabakken" N  ((((s l a) 1)) (((b A) 2) ((k @ n) 0))))
("slang" N ((((s l A N) 1))))
("slang" N ((((s l E N) 1))))
("spekvet" A ((((s p E k) 2)) (((v E t) 1))))
("spekvet" N ((((s p E k) 1)) (((v E t) 2))))
("stage" N  ((((s t a) 1) ((Z @) 0))))
("stage" N  ((((s t e) 1) ((G @) 0))))
("stand" N ((((s t A n t) 1))))
("stand" N ((((s t E n t) 1))))
("steengoed" N ((((s t e n) 1)) (((G u t) 2))))
("steengoed" A ((((s t e n) 2)) (((G u t) 1)))) 
("steenrood" N ((((s t e n) 1)) (((r o t) 2))))
("steenrood" A ((((s t e n) 2)) (((r o t) 1)))) 
("stelpen" N  ((((s t E l) 1)) (((p E n) 2))))
("stelpen" V  ((((s t E l) 1) ((p @ n) 0))))
("stemloos" A ((((s t E m) 1) ((l o s) 0))))
("stemloos" A ((((s t E m) 0) ((l o s) 1))))
("sterbladigen" A  ((((s t E r) 1)) (((b l a) 2) ((d @) 0) ((G @ n) 0))))
("sterbladigen" nil  ((((s t E r) 2)) (((b l a) 1) ((d @) 0) ((G @ n) 0))))
("subject" A  ((((s Y b) 1) ((j E k t) 0))))
("subject" N  ((((s Y b) 0) ((j E k t) 1))))
("subjekt" A  ((((s Y b) 1) ((j E k t) 0))))
("subjekt" N  ((((s Y b) 0) ((j E k t) 1))))
("substantief" A  ((((s Y p) 0) ((s t A n) 0) ((t i f) 1))))
("substantief" N  ((((s Y p) 1) ((s t A n) 0) ((t i f) 0))))
("suikerzoet" A ((((s Y+) 2) ((k @ r) 0)) (((z u t) 1))))
("suikerzoet" N ((((s Y+) 1) ((k @ r) 0)) (((z u t) 2))))
("superlatief" A ((((s y) 0) ((p @ r) 0) ((l A) 0) ((t i f) 1))))
("superlatief" A ((((s y) 1) ((p @ r) 0) ((l A) 0) ((t i f) 0))))
("taalpolitiek" A  ((((t a l) 2)) (((p o) 0) ((l i) 0) ((t i k) 1))))
("taalpolitiek" N  ((((t a l) 1)) (((p o) 0) ((l i) 0) ((t i k) 2))))
("touche" nil  ((((t u S) 1))))
("touche" nil  ((((t u) 0) ((S e) 1))))
("touché" nil ((((t u) 0) ((S e) 1))))
("tube" N ((((t y) 1) ((b @) 0))))
("tube" N ((((t y p) 1))))
("tureluurs" A  ((((t y) 0) ((r @) 0) ((l y r s) 1))))
("tureluurs" nil  ((((t y) 1) ((r @) 0)) (((l y r s) 2))))
("uitstekend" A  ((((Y+ t) 1)) (((s t e) 2) ((k @ n t) 0))))
("uitstekend" A  ((((Y+ t) 2)) (((s t e) 1) ((k @ n t) 0))))
("uitstékend" A ((((Y+ t) 2)) (((s t e) 1) ((k @ n t) 0))))
("uniform" A  ((((y) 0) ((n i) 0) ((f O r m) 1))))
("uniform" N  ((((y) 1) ((n i) 0) ((f O r m) 0))))
("veenkoloniaal" N ((((v e n) 1)) (((k o) 0) ((l o) 0) ((n i) 0) ((j a l) 2))))
("veenkoloniaal" A ((((v e n) 2)) (((k o) 0) ((l o) 0) ((n i) 0) ((j a l) 1))))
("verfrommel" N  ((((v E r f) 1)) (((r O) 2) ((m @ l) 0))))
("verfrommel" V  ((((v @ r) 0) ((f r O) 1) ((m @ l) 0))))
("verheid" N  ((((v E r) 1) ((h E+ t) 0))))
("verheid" V  ((((v @ r) 0) ((h E+ t) 1))))
("verkopen" N  ((((v E r) 1)) (((k o) 2) ((p @ n) 0))))
("verkopen" V  ((((v @ r) 0) ((k o) 1) ((p @ n) 0))))
("verkópen" V ((((v @ r) 0) ((k o) 1) ((p @ n) 0))))
("verspringen" V ((((v E r) 1)) (((s p r I) 2) ((N @ n) 0))))
("verspringen" V ((((v @ r) 0) ((s p r I) 1) ((N @ n) 0))))
("ververs" N  ((((v E r) 1) ((v @ r s) 0))))
("ververs" V  ((((v @ r) 0) ((v E r s) 1))))
("vocativus" N ((((v o) 0) ((k a) 0) ((t i) 1) ((v Y s) 0))))
("vocativus" A ((((v o) 1) ((k a) 0) ((t i) 0) ((v Y s) 0))))
("volbouwde" A  ((((v O l) 2)) (((b A+ w) 1) ((d @) 0))))
("volbouwde" V  ((((v O l) 1)) (((b A+ w) 2) ((d @) 0))))
("voorhanden" A  ((((v o r) 2)) (((h A n) 1) ((d @ n) 0))))
("voorhanden" N  ((((v o r) 1)) (((h A n) 2) ((d @ n) 0))))
("voorkomen" V  ((((v o r) 1)) (((k o) 2) ((m @ n) 0))))
("voorkomen" V  ((((v o r) 2)) (((k o) 1) ((m @ n) 0))))
("voorkómen" V ((((v o r) 0)) (((k o) 1) ((m @ n) 0))))
("voorkomend" A  ((((v o r) 1)) (((k o) 2) ((m @ n t) 0))))
("voorkomend" A  ((((v o r) 2)) (((k o) 1) ((m @ n t) 0))))
("voornaam" A  ((((v o r) 0) ((n a m) 1))))
("voornaam" N  ((((v o r) 1)) (((n a m) 2))))
("voornemens" ADV  ((((v o r) 2)) (((n e) 1) ((m @ n s) 0))))
("voornemens" N  ((((v o r) 1)) (((n e) 2) ((m @ n s) 0))))
("voornáám" A ((((v o r) 0) ((n a m) 1))))
("voorschreven" N  ((((v o r) 1)) (((s x r e) 2) ((v @ n) 0))))
("voorschreven" V  ((((v o r) 2)) (((s x r e) 1) ((v @ n) 0))))
("voorspel" N  ((((v o r) 1)) (((s p E l) 2))))
("voorspel" V  ((((v o r) 2)) (((s p E l) 1))))
("voorspellen" N  ((((v o r) 1) ((s p E) 0) ((l @ n) 0))))
("voorspellen" V  ((((v o r) 0) ((s p E) 1) ((l @ n) 0))))
("vooruitgang" N ((((v o r) 1)) (((Y+ t) 2) ((G A N) 0))))
("vooruitgang" N ((((v o) 2)) (((r Y+ t) 1) ((G A N) 0))))
("vooruitzicht" N ((((v o r) 1)) (((Y+ t) 2) ((z I x t) 0))))
("vooruitzicht" N ((((v o) 2)) (((r Y+ t) 1) ((z I x t) 0))))
("voortvarende" A  ((((v o r t) 2)) (((f a) 1) ((r @ n) 0) ((d @) 0))))
("voortvarende" nil  ((((v o r t) 1)) (((f a) 2) ((r @ n) 0) ((d @) 0))))
("voorzegde" N  ((((v o r) 1)) (((z E G) 2) ((d @) 0))))
("voorzegde" V  ((((v o r) 2)) (((z E G) 1) ((d @) 0))))
("voorzeggen" N  ((((v o r) 1)) (((z E) 2) ((G @ n) 0))))
("voorzeggen" V  ((((v o r) 2)) (((z E) 1) ((G @ n) 0))))
("vérkopen" N ((((v E r) 1) ((k o) 0) ((p @ n) 0))))
("vóórkomen" V ((((v o r) 1)) (((k o) 0) ((m @ n) 0))))
("vóórnaam" N ((((v o r) 1) ((n a m) 0))))
("wasbleek" N ((((w A s) 1)) (((b l e k) 2))))
("wasbleek" A ((((w A s) 2)) (((b l e k) 1))))
("weergalm" N  ((((w e r) 1)) (((G A l m) 2))))
("weergalm" V  ((((w e r) 2)) (((G A l m) 1))))
("weerschijn" A  ((((w e r) 2)) (((s x E+ n) 1))))
("weerschijn" N  ((((w e r) 1)) (((s x E+ n) 2))))
("werkeloze" A  ((((w E r) 0) ((k @) 0) ((l o) 1) ((z @) 0))))
("werkeloze" N  ((((w E r) 1) ((k @) 0) ((l o) 0) ((z @) 0))))
("werkgelegenheid" N ((((w E r k) 1)) (((G @) 0) ((l e) 2) ((G @ n) ((h E+ t) 0)))))
("werkgelegenheid" N ((((w E r k) 2)) (((G @) 0) ((l e) 1) ((G @ n) ((h E+ t) 0)))))
("werkloze" A  ((((w E r k) 0) ((l o) 1) ((z @) 0))))
("werkloze" N  ((((w E r k) 1) ((l o) 0) ((z @) 0))))
("wintergroen" N ((((w I n) 1) ((t @ r) 0)) (((G r u n) 2))))
("wintergroen" A ((((w I n) 2) ((t @ r) 0)) (((G r u n) 1))))
("zeegroen" N ((((z e) 1)) (((G r u n) 2))))
("zeegroen" A ((((z e) 2)) (((G r u n) 1))))
("zoeven" ADV  ((((z o) 2)) (((w e) 1) ((v @ n) 0))))
("zoeven" V  ((((z u) 1) ((v @ n) 0))))
("zoëven" ADV ((((z o) 0)) (((w e) 1) ((v @ n) 0))))
("één" nil ((((e n) 1))))