;; --------------------------------------------------------------------------------
;; Characters
;; --------------------------------------------------------------------------------

;; alphabetic characters
("a" char ((((a) 1))))
("b" char ((((b e) 1))))
("c" char ((((s e) 1))))
("d" char ((((d e) 1))))
("e" char ((((e) 1))))
("f" char ((((E f) 1))))
("g" char ((((x e) 1))))
("h" char ((((h a) 1))))
("i" char ((((i) 1))))
("j" char ((((j e) 1))))
("k" char ((((k a) 1))))
("l" char ((((E l) 1))))
("m" char ((((E m) 1))))
("n" char ((((E n) 1))))
("o" char ((((o) 1))))
("p" char ((((p e) 1))))
("q" char ((((k y) 1))))
("r" char ((((E r) 1))))
("s" char ((((E s) 1))))
("t" char ((((t e) 1))))
("u" char ((((y) 1))))
("v" char ((((v e) 1))))
("w" char ((((w e) 1))))
("x" char ((((I k s) 1))))
("y" char ((((E+) 1))))
("z" char ((((z E t) 1))))

;; vowels with diacritics
("á" nil nil (a accent acute)) 
("à" nil nil (a accent grave))
("ä" nil nil (a trema)) 
("â" nil nil (a circumflex)) 
("é" nil nil (e accent acute)) 
("è" nil nil (e accent grave))
("ë" nil nil (e trema)) 
("ê" nil nil (e circumflex))     
("í" nil nil (i accent acute)) 
("ì" nil nil (i accent grave))
("ï" nil nil (i trema)) 
("î" nil nil (i circumflex)) 
("ó" nil nil (o accent acute)) 
("ò" nil nil (o accent grave))
("ö" nil nil (o trema)) 
("ô" nil nil (o circumflex)) 
("ú" nil nil (u accent acute)) 
("ù" nil nil (u accent grave))
("ü" nil nil (u trema)) 
("û" nil nil (u circumflex)) 

("Á" nil nil (a accent acute)) 
("À" nil nil (a accent grave))
("Ä" nil nil (a trema)) 
("Â" nil nil (a circumflex)) 
("É" nil nil (e accent acute)) 
("È" nil nil (e accent grave))
("Ë" nil nil (e trema)) 
("Ê" nil nil (e circumflex))     
("Í" nil nil (i accent acute)) 
("Ì" nil nil (i accent grave))
("Ï" nil nil (i trema)) 
("Î" nil nil (i circumflex)) 
("Ó" nil nil (o accent acute)) 
("Ò" nil nil (o accent grave))
("Ö" nil nil (o trema)) 
("Ô" nil nil (o circumflex)) 
("Ú" nil nil (u accent acute)) 
("Ù" nil nil (u accent grave))
("Ü" nil nil (u trema)) 
("Û" nil nil (u circumflex)) 


;; digits
("0" num ((((n Y l) 1))))
("1" num ((((e n) 1))))
("2" num ((((t w e) 1))))
("3" num ((((d r i) 1))))
("4" num ((((v i r) 1))))
("5" num ((((v E+ f) 1))))
("6" num ((((z E s) 1))))
("7" num ((((z e) 1) ((v @ n) 0))))
("8" num ((((A x t) 1))))
("9" num ((((n e) 1) ((G @ n) 0))))

;; non-alphanumeric chars with a single-word pronounciation
("." char ((((p Y n t) 1))))
(";" char ((((p Y n t) 0)) (((k O) 1) ((m a) 0))))
("," char ((((k O) 1) ((m a) 0))))
("?" char ((((v r a x) 1)) (((t e) 2) ((k @ n) 0))))
("!" char ((((Y+ t) 1)) (((r u p) 2)) (((t e) 2) ((k @ n) 0))))
("'" char ((((a n) 1) ((h a) 0) ((l I N s) 0)) (((t e) 2) ((k @ n) 0)))) 
("`" char ((((a n) 1) ((h a) 0) ((l I N s) 0)) (((t e) 2) ((k @ n) 0)))) 
("#" char ((((h E k) 1) ((j @) 0))))
("$" char ((((d O) 1) ((l A r) 0)) (((t e) 2) ((k @ n) 0))))
("%" char ((((p r o) 2)) (((s E n t) 1))))
("^" char ((((d A k) 1) ((j @) 0))))
("&" char((((E) 1)) (((p E r) 2) ((s E n t) 0)) ))
("+" char((((p l Y s) 1)) (((t e) 2) ((k @ n) 0))))
("~" char ((((t I l) 1) ((d @) 0))))
("(" char ((((o) 1) ((p @) 0) ((n I N s) 0)) (((h a k) 2) ((j @) 0))))
(")" char ((((s l Y+ t) 1)) (((h a k) 2) ((j @) 0))))
("[" char ((((o) 1) ((p @) 0) ((n I N s) 0)) (((h a k) 2) ((j @) 0))))
("]" char ((((s l Y+ t) 1)) (((h a k) 2) ((j @) 0))))
("{" char ((((o) 1) ((p @) 0) ((n I N s) 0))(((A) 0) ((k o) 0) ((l a) 2) ((d @) 0))))
("}" char ((((s l Y+ t) 1)) (((A) 0) ((k o) 0) ((l a) 2) ((d @) 0))))
;; ambiguous tokens
("@" char ((((a) 1) ((p @) 0)) (((s t a r) 2) ((t j @) 0)))) 
("@" email ((((E t) 1))))
("-" char ((((s t r e p) 1))))
("-" math ((((m I n) 1))))
("*" char ((((s t E) 1) ((r @) 0) ((t j @) 0))))
("*" math ((((m a l) 1))))

;; non-alphanumeric chars with a multi-word pronounciation
(":" nil nil (dubbele punt)) 
("\\" nil nil (schuine streep)) 
("_" nil nil (liggende streep)) 
("|" nil nil (rechte streep)) 
("\"" nil nil (dubbele aanhalingstekens)) 
("=" nil nil (is gelijk teken)) 
("<" nil nil (kleiner dan teken)) 
(">" nil nil (groter dan teken))
;; ambiguous tokens
("/" char nil (schuine streep)) 
("/" math nil (gedeeld door)) 

;; --------------------------------------------------------------------------------
;; Numbers
;; --------------------------------------------------------------------------------

("nul" nil  ((((n Y l) 1))))
("een" Num  ((((e n) 1))))
("eenen" nil  ((((e) 1) ((n @ n) 0))))
("twee" nil  ((((t w e) 1))))
("tweeen" nil  ((((t w e) 1) ((j @ n) 0))))
("drie" nil  ((((d r i) 1))))
("drieen" nil  ((((d r i) 1) ((j @ n) 0))))
("vier" nil  ((((v i r) 1))))
("vieren" nil  ((((v i) 1) ((r @ n) 0))))
("vijf" nil  ((((v E+ f) 1))))
("vijfen" nil  ((((v E+ f) 1) ((@ n) 0))))
("zes" nil  ((((z E s) 1))))
("zesen" nil  ((((z E) 1) ((s @ n) 0))))
("zeven" nil  ((((z e) 1) ((v @ n) 0))))
("zevenen" nil  ((((z e) 1) ((v @) 0) ((n @ n) 0))))
("acht" nil  ((((A x t) 1))))
("achten" nil  ((((A x) 1) ((t @ n) 0))))
("negen" nil  ((((n e) 1) ((G @ n) 0))))
("negenen" nil  ((((n e) 1) ((G @) 0) ((n @ n) 0))))
("tien" nil  ((((t i n) 1))))
("elf" nil  ((((E l f) 1))))
("twaalf" nil  ((((t w a l f) 1))))
("dertien" nil  ((((d E r) 1)) (((t i n) 2))))
("veertien" nil  ((((v e r) 1)) (((t i n) 2))))
("vijftien" nil  ((((v E+ f) 1)) (((t i n) 2))))
("zestien" nil  ((((z E s) 1)) (((t i n) 2))))
("zeventien" nil  ((((z e) 1) ((v @ n) 0)) (((t i n) 2))))
("achttien" nil  ((((A x) 1)) (((t i n) 2))))
("negentien" nil  ((((n e) 1) ((G @ n) 0)) (((t i n) 2))))
("twintig" nil  ((((t w I n) 1) ((t @ x) 0))))
("dertig" nil  ((((d E r) 1) ((t @ x) 0))))
("veertig" nil  ((((v e r) 1) ((t @ x) 0))))
("vijftig" nil  ((((v E+ f) 1) ((t @ x) 0))))
("zestig" nil  ((((z E s) 1) ((t @ x) 0))))
("zeventig" nil  ((((z e) 1) ((v @ n) 0) ((t @ x) 0))))
("tachtig" nil  ((((t A x) 1) ((t @ x) 0))))
("negentig" nil  ((((n e) 1) ((G @ n) 0) ((t @ x) 0))))
("honderd" nil  ((((h O n) 1) ((d @ r t) 0))))
("duizend" nil  ((((d Y+) 2) ((z @ n t) 0))))
("miljoen" nil  ((((m @ l) 0) ((j u n) 1))))
("miljard" nil  ((((m @ l) 0) ((j A r t) 1))))


;; --------------------------------------------------------------------------------
;; reduced forms
;; --------------------------------------------------------------------------------

;; 'k, 'm, 'n, 't, 'r
("k" red ((((@ k) 1))))
("m" red ((((@ m) 1))))
("n" red ((((@ n) 1))))
("t" red ((((@ t) 1))))
("r" red ((((@ r) 1))))
;; 's as reduced genetive, e.g. 's morgens
("s" gen ((((@ s) 1))))

;; --------------------------------------------------------------------------------
;; Abbreviations
;; --------------------------------------------------------------------------------

;; single dot
("prof." nil nil (professor))
("dr." nil nil (doctor))
("drs." nil nil (doctorandes))
("ir." nil nil (ingenieur))
("mr." nil nil (meester))

;; multiple dot
("a.d." nil nil (aan de))
("a.i." nil nil (ad interim))
("a.s." nil nil (aanstaande))
("a.u.b." nil nil (alstublieft))
("b.d." nil nil (buiten dienst))
("b.v." nil nil (bij voorbeeld))
("b.w." nil nil (burgelijk wetboek))
("c.q." nil nil (c q))
("c.a." nil nil (circa))
("c.s." nil nil (cum suis))
("c.v." nil nil (c v))
("d.i." nil nil (dat is))
("e.a." nil nil (en andere))
("e.d." nil nil (en dergelijke))
("e.g." nil nil (bijvoorbeeld))
("e.o." nil nil (en omstreken))
("e.v." nil nil (en volgende))
("e.e.a." nil nil (een en ander))
("e.v.a." nil nil (en vele andere))
("d.d." nil nil (de data))
("d.w.z." nil nil (dat wil zeggen))
("i.e." nil nil (dat wil zeggen))
("i.o." nil nil (in oprichting))
("i.p.v." nil nil (in plaats van))
("i.s.m." nil nil (in samenwerking met))
("i.v.m." nil nil (in verband met))
("j.l." nil nil (jongstleden))
("m.a.w." nil nil (met andere woorden))
("m.b.t." nil nil (met betrekking tot))
("m.i." nil nil (mijns inziens))
("m.m.v." nil nil (met medewerking van))
("m.u.v." nil nil (met uitzondering van))
("m.n." nil nil (met name))
("n.b." nil nil (nota bene))
("n.C." nil nil (na Christus))
("n.Chr." nil nil (na Christus))
("n.l." nil nil (namelijk))
("n.v." nil nil (n v))
("n.a.v." nil nil (naar aanleiding van))
("o.a." nil nil (onder andere))
("o.i." nil nil (ons inziens))
("o.i.d." nil nil (of iets dergelijks))
("o.k." nil nil (okay))
("o.l.v." nil nil (onder leiding van))
("o.m." nil nil (onder meer))
("o.v." nil nil (openbaar vervoer))
("o.v.v." nil nil (onder vermelding van))
("p.a." nil nil (per adres))
("p.o." nil nil (per ommegaande))
("p.p." nil nil (per persoon))
("p.r." nil nil (p r))
("r.k." nil nil (rooms katholiek))
("s.v.p." nil nil (s v p))
("tel.nr." nil nil (telefoonnummer))
("t.b.v." nil nil (ten behoeve van))
("t.a.v." nil nil (ten aanzien van))
("t.e.m." nil nil (tot en met))
("t.g.v." nil nil (ten gevolge van))
("t.n.v." nil nil (ten name van))
("t.o.v." nil nil (ten opzichte van))
("t.v." nil nil (televisie))
("t.w." nil nil (te weten))
("t.w.v." nil nil (ter waarde van))
("t.z.t." nil nil (ter zijner tijd))
("v.a." nil nil (van af))
("v.C." nil nil (voor Christus))
("v.Chr." nil nil (voor Christus))
("v.d." nil nil (van de))
("v.l.n.r." nil nil (van links naar rechts))
("w.c." nil nil (w c))
("z.g." nil nil (zogenaamd))
("z.s.m." nil nil (zo spoedig mogelijk))

;; --------------------------------------------------------------------------------
;; Acronyms
;; --------------------------------------------------------------------------------

;; containing vowels
("uvt" nil nil (u v t))